# Fundamentals of Data Science
Winter Semester 2020

## Prof. Fabio Galasso, Alessandro Flaborea and Luca Franco
<galasso@di.uniroma1.it>, <flaborea.1841969@studenti.uniroma1.it>, <franco.luca.17@gmail.com>

## Exercise 2

In Exercise 2, you will re-derive and implement logistic regression and optimize the parameters with Gradient Descent and with the Newton's method. Also, in this exercise you will re-derive and implement Gassian Discriminant Analysis.
We will use the files logistic_x.txt and logistic_y.txt. The first contains the feature values $x^{(i)}_1$ and $x^{(i)}_2$ for the $i$-th data sample $x^{(i)}$. The second contains the ground truth label $y^{(i)}$ for each corresponding data sample.

Note that, differently from what seen in lecture, $y^{(i)}\in \{-1,1\}$.

The completed exercise should be handed in as a single notebook file. Use Markdown to provide equations. Use the code sections to provide your scripts and the corresponding plots.
Submit it by sending an email to galasso@di.uniroma1.it, flaborea.1841969@studenti.uniroma1.it and franco.luca.17@gmail.com by Wednesday November 25th, 23:59.

## Notation

- $x^i$ is the $i^{th}$ feature vector
- $y^i$ is the expected outcome for the $i^{th}$ training example
- $m$ is the number of training examples
- $n$ is the number of features

Let's start by setting up our Python environment and importing the required libraries:


## [15 points] Question 1: Logistic Regression with Gradient Ascent

### (a) [5 points] Equations for the log likelihood, its gradient, and the gradient ascent update rule.

Write and simplify the likelihood $L(\theta)$ and log-likelihood $l(\theta)$ of the parameters $\theta$.

Recall the probabilistic interpretation of the hypothesis $h_\theta(x)= P(y=1|x;\theta)$ and that $h_\theta(x)=\frac{1}{1+\exp(-\theta^T x)}$.

Also derive the gradient $\frac{\delta l(\theta)}{\delta \theta_j}$ of $l(\theta)$ and write the gradient update equation. 

Question: in order to learn the optimal $\theta$, do you need to minimize or to maximize $l(\theta)$?

################# Do not write above this line #################

$P(Y=1|X=x) \quad = \quad \sigma(h) \quad \mbox{t.c.} \quad h_\theta(x) \quad = \quad \theta^Tx \quad = \quad \sum_{i=1}^{n}\theta_i x_i$ 

$P(Y=0|X=x) \quad = \quad (1-\sigma(\theta^Tx))$

$\sigma(\theta^Tx)\quad = \quad\frac{1}{1 + exp(-\theta^Tx)} \quad$ sigmoid function $\quad \mbox{t.c.} 0 < \sigma(\theta^Tx) < 1  \quad \forall x  \in R $ 

$P(X=y|X=x) \quad =\quad \sigma(\theta^Tx)^y[1-\sigma(\theta^Tx)]^{ 1-y}  \quad $     probability mass function Bernoulli  

for $y= y_1, y_2 ... y_n \quad $ i.i.d prob $ \quad \longrightarrow \quad \prod_{i=1}^{n} P(X=y_i|X=x_i) \quad = \quad L(\theta)\quad $  likelihood function 

$L(\theta) \quad =  \quad\prod_{i=1}^{n} P(X=y_i|X=x_i) \quad = \quad \prod_{i=1}^{n} \sigma(\theta^Tx)^y[1-\sigma(\theta^Tx)]^{ 1-y} $

$l(\theta)  \quad = \quad lnL(\theta)\quad =\quad  \sum_{i=1}^{n} (y_i ln(\sigma(\theta^Tx_i)) + (1-y_i)ln[1-\sigma(\theta^Tx_i) ] $ 
 
$ \nabla l(\theta) \quad = \quad (\frac{\delta l(\theta}{\delta \theta_1}, \frac{\delta l(\theta}{\delta \theta_2}....) \quad$ with $ j = 1,2,...$  

$\frac{\delta l(\theta)}{\delta \theta_j} \quad =\quad  \frac{\delta}{\delta \theta_j} ( \sum_{i=1}^{n} (y_i ln(\sigma(\theta^Tx_i)) + (1-y_i)ln[1-\sigma(\theta^Tx_i) ] ) $

$\frac{\delta l(\theta)}{\delta \theta_j}  \quad = \sum_{i=1}^{n} [ y_i\frac{1}{\sigma(\theta^Tx_i)}\frac{\delta \sigma(\theta^Tx_i)}{\delta \theta_i} + (1-y_i)\frac{1}{1-\sigma\theta^Tx_i}(\frac{-\delta\sigma(\theta^Tx_i)}{\sigma \theta_i}) ]$ 

$ \frac{\delta l(\theta)}{\delta \theta_j} \quad = \sum_{i=1}^{n} [ y_i\frac{1}{\sigma(\theta^Tx_i}x_{ ij}\frac{\exp(-\theta^Tx_i)}{(1+\exp(-\theta^Tx_i)} + (1-y_i)\frac{1+ \exp(-\theta^Tx_i)}{\exp(-\theta^Tx_i)}(\frac{-x_{ ij} \exp(-\theta^Tx)}{(1+\exp(-\theta^Tx)^2}) ]$ 

$ \frac{\delta l(\theta)}{\delta \theta_j}  \quad = \sum_{i=1}^{n} [  y_i x_{ ij} \frac{\exp(-\theta^Tx_i)}{1+ \exp(-\theta^Tx_i)} + (1-y_i)\frac{x_{ ij}}{1+\exp(-\theta^Tx_i}] $ 

$\frac{\delta l(\theta)}{\delta \theta_j} \quad = \sum_{i=1}^{n} [\sigma(\theta^Tx_i)[y_i x_{ ij} \exp(-\theta^Tx_i) + ( y_i-1)x_{ ij}] \quad = \quad \sigma(\theta^Tx_i)x_{ ij}[y_i \exp(-\theta^Tx_i) + y_i -1)]] $ 

$\frac{\delta l(\theta)}{\delta \theta_j} \quad = \sum_{i=1}^{n} [ \sigma(\theta^Tx_i)x_{ ij}[y_i(\exp(-\theta^Tx_i) + 1 )- 1 ] \quad = \quad \sigma(\theta^Tx_i)x_{ ij}[\frac{y_i}{\sigma(theta^Tx_i)} - 1] \quad = \quad x_{ ij}[y_i -\sigma(\theta^Tx_i)]]$ 

$\frac{\delta l(\theta)}{\delta \theta_j} \quad = \sum_{i=1}^{n} [ x_{ij}[y_i -\sigma(\theta^Tx_i)]]$ 
 
In order to learn the optimal $\theta$ we need to "maximize" $l(\theta)$


################# Do not write below this line #################

### (b) [10 points] Implementation of logistic regression with Gradient Ascent

Code up the equations above to learn the logistic regression parameters. Consider as data the files logistic_x.txt and logistic_y.txt. The first contains the feature values $x^{(i)}_1$ and $x^{(i)}_2$ for the $i$-th data sample $x^{(i)}$. The second contains the ground truth label $y^{(i)}$ for each corresponding data sample.

In [5]:
%matplotlib inline
import numpy as np # imports a fast numerical programming library
import scipy as sp # imports stats functions, amongst other things
import matplotlib as mpl # this actually imports matplotlib
import matplotlib.cm as cm # allows us easy access to colormaps
import matplotlib.pyplot as plt # sets up plotting under plt
import pandas as pd # lets us handle data as dataframes
import math as m

# sets up pandas table display
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)

import seaborn as sns # sets up styles and gives us more plotting options

Let's start by loading the data into two pandas DataFrames:

In [178]:
df_x = pd.read_csv("./data/logistic_x.txt", sep="\ +", names=["x1","x2"], header=None, engine='python')
df_y = pd.read_csv('./data/logistic_y.txt', sep='\ +', names=["y"], header=None, engine='python')
df_y = df_y.astype(int)
df_x 

x1        x2
0   1.343250 -1.331148
1   1.820553 -0.634668
2   0.986321 -1.888576
3   1.944373 -1.635452
4   0.976734 -1.353315
..       ...       ...
94  4.774854  0.099415
95  5.827485 -0.690058
96  2.289474  1.970760
97  2.494152  1.415205
98  2.084795  1.356725

[99 rows x 2 columns]

In [179]:
df_y

y
0  -1
1  -1
2  -1
3  -1
4  -1
.. ..
94  1
95  1
96  1
97  1
98  1

[99 rows x 1 columns]

Let's get the NumPy arrays from the dataset, and add a column of 1's to $X$ to take into account the zero intercept

In [180]:
x = np.hstack([np.ones((df_x.shape[0], 1)), df_x[["x1","x2"]].values])
y = df_y["y"].values
y

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

Adjust y so that $y^{(i)}\in [0,1]$

################# Do not write above this line #################

Your code here

In [206]:
y = (df_y["y"].values +1)/2
y = y.astype(int)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

################# Do not write below this line #################

In [182]:
[x[:5,:],x[-5:,:]] # Plot the first and last 5 lines of x, now containing features x0 (constant=1), x1 and x2

[array([[ 1.        ,  1.3432504 , -1.3311479 ],
        [ 1.        ,  1.8205529 , -0.6346681 ],
        [ 1.        ,  0.98632067, -1.8885762 ],
        [ 1.        ,  1.9443734 , -1.635452  ],
        [ 1.        ,  0.97673352, -1.3533151 ]]),
 array([[ 1.        ,  4.7748538 ,  0.09941521],
        [ 1.        ,  5.8274854 , -0.69005848],
        [ 1.        ,  2.2894737 ,  1.9707602 ],
        [ 1.        ,  2.494152  ,  1.4152047 ],
        [ 1.        ,  2.0847953 ,  1.3567251 ]])]

In [183]:
theta = np.array([-2,1,2])

theta_test*x[1]

(np.exp(-theta*x[1]))

g = 1/(1 + np.exp(-np.inner(theta,x[1])))
    
print(g)


pow(2,3)

0.19018888795670227


8

In [184]:
[y[:5],y[-5:]] # Plot the first and last 5 lines of y

[array([0, 0, 0, 0, 0]), array([1, 1, 1, 1, 1])]

Define the sigmoid function "sigmoid", the function to compute the gradient of the log likelihood  "grad_l" and the gradient ascent algorithm.

################# Do not write above this line #################

Your code here

################# Do not write below this line #################

In [198]:
def sigmoid(x, theta):
    
    g = 1/(1 + np.exp(-np.inner(theta,x)))
    

    return g

def log_likelihood(theta,x,y):
    pass # return the log likehood of theta according to data x and label y

    
    log_L = 0
    
    for i in range(99):
          
        X = y[i]*np.log(sigmoid(x[i], theta)) + (1-y[i])*np.log(1-sigmoid(x[i], theta)) #NaturAL LOGARITM???
        
        log_L = log_L + X
        
    return log_L/99


def grad_l(theta, x, y):
    
    G = np.zeros(3)
    
    for j in range (3):
        
        for i in range (len(y)):

            X = x[i][j]*(y[i] - sigmoid(x[i], theta)) 

            G[j] = G[j] + X
        
        
    
    pass # return the gradient G of the log likelihood
    return G

    
def gradient_ascent(theta,x,y,G,alpha,iterations):
    
    theta_n = np.zeros((99,3))   
    log_l_history = np.zeros(iterations)  
    theta_history = np.zeros((iterations,3))
    
    for k in range (iterations):
        
        
        D = grad_l(theta, x, y)

        for j in range(3):

            theta_history[k][j] = theta[j] 

            theta_history[k][j] = theta_history[k][j] +  alpha* D[j]

            theta[j] = theta_history[k][j] 

        log_l_history[k] = log_likelihood(theta,x,y)     
        
        
    
 #       log_l_history = log_likelihood(theta_history[i],x,y)

        
        
   
    
    
    

    pass # return the optimized theta parameters,
        # as well as two lists containing the log likelihood's and values of theta at all iterations
        
    return theta, log_l_history, theta_history

Check your grad_l implementation:
grad_l applied to the theta_test (defined below) should provide a value for log_l_test close to the target_value (defined below); in other words the error_test should be 0, up to machine error precision.

In [199]:
target_value = -0.4250958770469834
theta_test = np.array([-2,1,2])

log_l_test  = log_likelihood(theta_test,x,y)
error_test = np.abs(log_l_test - target_value)

print(log_l_test)

print("{:f}".format(error_test))

-0.4250958770469833
0.000000


Let's now apply the function gradient_ascent and print the final theta as well as theta_history 

In [202]:
# Initialize theta0
theta0 = np.zeros(x.shape[1])


# Run Gradient Ascent method
n_iter=3000
theta_final, log_l_history, theta_history = gradient_ascent(theta0,x,y,grad_l,alpha=0.001,iterations=n_iter)
print(theta_final)
print(theta_history)
#print(log_l_history)

log_l_test  = log_likelihood(theta_final,x,y)
print (log_l_test)
error_test = np.abs(log_l_test - target_value)
print("{:f}".format(error_test))

[-2.60769941  0.75755435  1.17100849]
[[-5.00000000e-04  4.76690475e-02  5.49282319e-02]
 [-5.10928684e-03  7.40460156e-02  1.06360363e-01]
 [-1.16221750e-02  8.98927900e-02  1.54269126e-01]
 ...
 [-2.60765702e+00  7.57545032e-01  1.17100540e+00]
 [-2.60767823e+00  7.57549696e-01  1.17100695e+00]
 [-2.60769941e+00  7.57554352e-01  1.17100849e+00]]
-0.3291488718892122
0.095947


Let's plot the log likelihood over iterations

In [203]:
fig,ax = plt.subplots(num=2)

ax.set_ylabel('l(Theta)')
ax.set_xlabel('Iterations')
_ = ax.plot(range(len(log_l_history)),log_l_history,'b.')

Plot the data and the decision boundary:

In [207]:
df_x_pl = df_x.copy()
df_y_pl = df_y.copy()
df_x_pl.insert(0, "y", y)
df_x_pl["y"] = pd.to_numeric(df_x_pl["y"], downcast='signed')
df_x_pl.head()


y        x1        x2
0  0  1.343250 -1.331148
1  0  1.820553 -0.634668
2  0  0.986321 -1.888576
3  0  1.944373 -1.635452
4  0  0.976734 -1.353315

In [208]:
# Generate vector to plot decision boundary
x1_vec = np.linspace(df_x_pl["x1"].min(),df_x_pl["x1"].max(),2);

# Plot raw data
sns.scatterplot(x = "x1", y = "x2", hue = "y", data = df_x_pl);

# Plot decision boundary
plt.plot(x1_vec,(-x1_vec*theta_final[1]-theta_final[0])/theta_final[2], color="red");

# Save the theta_final value for later comparisons
theta_GA = theta_final.copy()

################# Do not write above this line #################

Write now your considerations. Discuss in particular:
- what effects do the learning rate $\alpha$ and the number of iterations have on the computed $\theta$
- may you still achieve the same value if you decrease the learning rate $\alpha$ and increase the number of iterations n_iter up to an infinite number of them? Why?
- may you still achieve the same value if you increase the learning rate $\alpha$ substantially and decrease the number of iterations n_iter? Why?

Substantiate your answer with experiments and plots of the $l(\theta)$ and the decision boundary.

################# Do not write below this line #################


## [15 points] Question 2: Logistic Regression with the Newton's method

### (a) [5 points] Equations for the Hessian of the log likelihood

Derive the equation for the Hessian matrix $H$ of the log-likelihood $l(\theta)$ of the parameters $\theta$.

Recall that: $H_{i,j} = \frac{\delta^2 l(\theta)}{\delta \theta_i \delta \theta_j}$

Also write the parameter update rule for the Newton's method, as a function of the Hessian and gradient of $l(\theta)$.

Question: in order to learn the optimal $\theta$, do you need to minimize or to maximize $\nabla_{\theta} l$?

################# Do not write above this line #################

$\frac{\delta l(\theta)}{\delta \theta_j} \quad = \sum_{i=1}^{n} [ x_{ij}[y_i -\sigma(\theta^Tx_i)]] \quad  \longrightarrow \quad H_{ l(\theta)}  = \begin{pmatrix}
\frac{\delta^2 l(\theta)}{\delta \theta_j^2 } & \frac{\delta^2 l(\theta)}{\delta \theta_j \delta \theta_k}  & ... \\
\frac{\delta^2 l(\theta)}{\delta \theta_k \delta \theta_j} & \frac{\delta^2 l(\theta)}{\delta \theta_k^2 }  & ... \\
... & ... & ...
\end{pmatrix}   
\quad $ for j rows and k columns

$\frac{\delta^2 l(\theta)}{\delta \theta_j^2 } \quad = \quad -\sum_{i=1}^{n}[ x_{ ij}\frac{\delta}{\delta\theta_j}\sigma(\theta^Tx_i)] \quad  = \quad  \sum_{i=1}^{n}[-x_{ ij}^2\frac{\exp(-\theta^Tx_i)}{(1+\exp(-\theta^Tx_i))^2}] \quad  = \quad \sum_{i=1}^{n}[ -x_{ ij}^2\sigma^2(\theta^Tx_i)\exp(-\theta^Tx_i)] $

$ \frac{\delta^2 l(\theta)}{\delta \theta_j \delta \theta_k} \quad = \quad  \frac{\delta^2 l(\theta)}{\delta \theta_k \delta \theta_j} \quad = \quad \sum_{i=1}^{n}[ -x_{ ij} x_{ ik}\sigma^2(\theta^Tx_i)\exp(-\theta^Tx_i) ] $

$ H_{ l(\theta)} \quad = \quad - \sum_{i=1}^{n}\sigma^2(\theta^Tx_i)\exp(-\theta^Tx_i) \begin{pmatrix}
x_{ij}^2 & x_{ij} x_{ik}  & ... \\
x_{ik} x_{ij} & x_{ik}^2  & ... \\
... & ... & ...
\end{pmatrix}  $

-------------------------------------------------------------------------------------------------------------------------------

Newton method for 1D function $ y \quad = \quad f(x) $

$\quad y - f(x_n) \quad = \quad f'(x_n)(x-x_n) $ tangente a $f(x)$ in $(x_n, y_n)$

$ 0 = f'(x_n)(x_{ n+1}-x_n) + f(x_n) \quad $ with $ \quad y \longrightarrow 0 \quad$ and $ \quad x \longrightarrow x_{ n+1}$

$ x_n - \frac{f(x_n)}{f'(x_n)}  = x_{ n+1} \quad  \longrightarrow \quad f(x_{ n+1}) = y_{ n+1} $

check now $  \quad y_{ n+1}- y_n 	\approx 0 \quad $ if true we found root of $f(x)$, else do $ \quad y_n  = y_{ n+1} , \quad x_n  = x_{ n+1} \quad $ and reiterate.

-------------------------------------------------------------------------------------------------------------------------------

for N dimensions: $\quad \overline{\rm y} \quad = \quad f(\overline{\rm x}) \quad $ and $\quad f'(\overline{\rm x}) \quad = \quad \nabla f(\overline{\rm x}) $

$\overline{\rm x}_n - \frac{f(\overline{\rm x}_n)}{\nabla f(\overline{\rm x}_n)} = \overline{\rm x}_{ n+1} \quad $ with $ \quad \frac{1}{\nabla f(\overline{\rm x}_n)} \quad = \quad \nabla^-1 f(\overline{\rm x}_n) \quad \longrightarrow \quad \overline{\rm x}_{ n+1} \quad = \quad \overline{\rm x}_n - f(\overline{\rm x}_n)\nabla^-1 f(\overline{\rm x}_n)$


So in our case $\quad f(x) = \nabla l(\theta) \quad \longrightarrow \quad  \overline{\rm \theta}_{ n+1} = \overline{\rm \theta}_{ n} - H_{ l(\theta)}^-1 \nabla l(\theta)$

In order to learn the optimal $\theta$ which maximize $L(\theta)$ we need to find the roots of $\nabla l(\theta) $

################# Do not write below this line #################

### (b) [10 points] Implementation of logistic regression with the Newton's method

Code up the equations above to learn the logistic regression parameters. Consider as data the files logistic_x.txt and logistic_y.txt. The first contains the feature values  $x^{(i)}_1$ and $x^{(i)}_2$  for the  𝑖 -th data sample  $x^{(i)}$ . The second contains the ground truth label  $y^{(i)}$  for each corresponding data sample.

Define the Hessian function hess_l and the Newton's method function "newton":

################# Do not write above this line #################

Your code here

In [248]:
def hess_l(theta, x, y):
    
    hess = np.zeros((3,3))  
    
    for i in range(99):
        
        S = -pow(sigmoid(x[i], theta),2)*np.exp(-np.inner(theta,x[i]))
        
        for j in range(3):

            for k in range (3):
                
                hess[j][k] = hess[j][k] + x[i][j]*x[i][k]*S
                
    print(hess/99)
    
    return hess/99




def newton(theta0, x, y, G, H, eps):
    
    pass # return the optimized theta parameters,

        # as well as two lists containing the log likelihood's and values of theta at all iterations
    
    # return theta, theta_history, log_l_history
    
    
    

################# Do not write below this line #################

Check your hess_l implementation: hess_l applied to the theta_test (defined below) should provide a value for hess_l_test close to the target_value (defined below); in other words the error_test should be 0, up to machine error precision.

In [249]:
target_value = np.array([[-0.14357024, -0.43836134,  0.18767787], \
                         [-0.43836134, -1.72295801,  0.61817001], \
                         [ 0.18767787,  0.61817001, -0.51247901]])
theta_test=np.array([-2,1,2])

hess_l_test  = hess_l(theta_test,x,y)
error_test=np.sum(np.abs(hess_l_test-target_value),axis=(0,1))

print("{:f}".format(error_test))

[[-0.06348739 -0.20850539  0.0429698 ]
 [-0.20850539 -0.88639793  0.2139917 ]
 [ 0.0429698   0.2139917  -0.10705643]]
2.879550


Now run Newton's method to perform logistic regression:

In [193]:
# Initialize theta0
theta0 = np.zeros(x.shape[1])

# Run Newton's method
theta_final, theta_history, log_l_history = newton(theta0,x,y,grad_l,hess_l,1e-6)
print(theta_final)

TypeError: cannot unpack non-iterable NoneType object

Let's plot the log likelihood over iterations

In [ ]:
fig,ax = plt.subplots(num=2)

ax.set_ylabel('l(Theta)')
ax.set_xlabel('Iterations')
_=ax.plot(range(len(log_l_history)),log_l_history,'b.')

Plot the data and our decision boundary:

In [ ]:
df_x_pl=df_x.copy()
df_y_pl=df_y.copy()
df_x_pl.insert(0, "y", df_y)
df_x_pl["y"] = pd.to_numeric(df_x_pl["y"],downcast='signed')
df_x_pl.head()

In [ ]:
# Generate vector to plot decision boundary
x1_vec = np.linspace(df_x_pl["x1"].min(),df_x_pl["x1"].max(),2);

# Plot raw data
sns.scatterplot(x="x1", y="x2", hue="y", data=df_x_pl);

# Plot decision boundary
plt.plot(x1_vec,(-x1_vec*theta_final[1]-theta_final[0])/theta_final[2], color="red");

################# Do not write above this line #################

Write now your considerations. Discuss in particular:
- the different convergence speed of the Newton's method, compared to Gradient Ascent
- the incurred cost for the different convergence speed

################# Do not write below this line #################


## [7 points] Question 3: Logistic Regression with non linear boundaries

### (a) Polynomial features for logistic regression

Define new features, e.g. of 2nd and 3rd degrees, and learn a logistic regression classifier by using the new features, by using the Newton's optimization algorithm (or the gradient ascent one, if you like).

In particular, we would consider a polynomial boundary with equation:

$f(x_1, x_2) = c_0 + c_1 x_1 + c_2 x_2 + c_3 x_1^2 + c_4 x_2^2 + c_5 x_1 x_2 + c_6 x_1^3 + c_7 x_2^3 + c_8 x_1^2 x_2 + c_9 x_1 x_2^2$

We would therefore compute 7 new features: 3 new ones for the quadratic terms and 4 new ones for the cubic terms.

Create new arrays by stacking x (from the previous questions) and the new 7 features (in the order x1x1, x2x2, x1x2, x1x1x1, x2x2x2, x1x1x2, x1x2x2). In particular create x_new_quad by additionally stacking with x the quadratic features, and x_new_cubic by additionally stacking with x the quadratic and the cubic features.

In [ ]:
# First extract features x1 and x2 from x and reshape them to x1 vector arrays
x1 = x[:,1]
x2 = x[:,2]
x1 = x1.reshape(x1.shape[0], 1)
x2 = x2.reshape(x2.shape[0], 1)
print(x[:5,:]) # For visualization of the first 5 values
print(x1[:5,:]) # For visualization of the first 5 values
print(x2[:5,:]) # For visualization of the first 5 values

################# Do not write above this line #################

Your code here

In [ ]:
# Define features: x1x1, x2x2, x1x2, x1x1x1, x2x2x2, x1x1x2, x1x2x2

# Stack the features together together with x, to define
# x_new_quad [x, x1x1, x2x2, x1x2]
# and x_new_cubic [x, x1x1, x2x2, x1x2, x1x1x1, x2x2x2, x1x1x2, x1x2x2]

################# Do not write below this line #################

Now use the Newton's optimization algorithm to learn theta by maximizing the log-likelihood, both for the case of x_new_quad and x_new_cubic.

Note: you may alternatively use gradient ascent, as in Question 1, if you like.

In [ ]:
# Initialize theta0, in case of quadratic features
theta0_quad = np.zeros(x_new_quad.shape[1])

# Run Newton's method, in case of quadratic features
theta_final_quad, theta_history_quad, log_l_history_quad = newton(theta0_quad,x_new_quad,y,grad_l,hess_l,1e-6)

# Initialize theta0, in case of quadratic and cubic features
theta0_cubic = np.zeros(x_new_cubic.shape[1])

# Run Newton's method, in case of quadratic and cubic features
theta_final_cubic, theta_history_cubic, log_l_history_cubic = newton(theta0_cubic,x_new_cubic,y,grad_l,hess_l,1e-6)

# check and compare with previous results
print(theta_final_quad)
print(theta_final_cubic)

In [ ]:
# Plot the log likelihood values in the optimization iterations, in one of the two cases.
fig,ax = plt.subplots(num=2)

ax.set_ylabel('l(Theta)')
ax.set_xlabel('Iterations')
_=ax.plot(range(len(log_l_history_cubic)),log_l_history_cubic,'b.')

### (b) Plot the computed non-linear boundary and discuss the questions



First, define a boundary_function to compute the boundary equation for the input feature vectors $x_1$ and $x_2$, according to estimated parameters theta, both in the case of quadratic (theta_final_quad) and of quadratic and cubic features (theta_final_cubic). Refer for the equation to the introductory part of Question 3.

################# Do not write above this line #################

Your code here

In [ ]:
def boundary_function(x1_vec, x2_vec, theta_final):
    
    x1_vec, x2_vec = np.meshgrid(x1_vec,x2_vec)
    
    if len(theta_final) == 6:
        # boundary function value for features up to quadratic
        c_0, c_1, c_2, c_3, c_4, c_5 = theta_final
        # f =
    elif len(theta_final) == 10:
        # boundary function value for features up to cubic
        c_0, c_1, c_2, c_3, c_4, c_5, c_6, c_7, c_8, c_9 = theta_final
        # f = 
    else:
        raise("Number of Parameters is not correct")
        
    return x1_vec, x2_vec, f

################# Do not write below this line #################

Now plot the decision boundaries corresponding to the theta_final_quad and theta_final_cubic solutions.

In [ ]:
x1_vec = np.linspace(df_x_pl["x1"].min()-1,df_x_pl["x1"].max()+1,200);
x2_vec = np.linspace(df_x_pl["x2"].min()-1,df_x_pl["x2"].max()+1,200);

x1_vec, x2_vec, f = boundary_function(x1_vec, x2_vec, theta_final_quad)

sns.scatterplot(x="x1", y="x2", hue="y", data=df_x_pl);

plt.contour(x1_vec, x2_vec, f, colors="red", levels=[0])

In [ ]:
x1_vec = np.linspace(df_x_pl["x1"].min()-1,df_x_pl["x1"].max()+1,200);
x2_vec = np.linspace(df_x_pl["x2"].min()-1,df_x_pl["x2"].max()+1,200);

x1_vec, x2_vec, f = boundary_function(x1_vec, x2_vec, theta_final_cubic)

sns.scatterplot(x="x1", y="x2", hue="y", data=df_x_pl);

plt.contour(x1_vec, x2_vec, f, colors="red", levels=[0])

################# Do not write above this line #################

Write now your considerations. Discuss in particular:
- What happens if you further increase the degree of the polynomial. How would the boundary change? Would you incur underfitting or overfitting?
- Look at the boundary of the quadratic and cubic polynomial features. Do they meet your expectations? Why? Consider in particular the classifier decision boundary in areas where there are fewer training data, i.e. where the classifier is supposed to generalize. Hint: Try changing the minimum and maximum limits in vectors x1_vec and x2_vec before plotting the boundaries.
- Look at the values of the original features, the 2nd and 3rd degree ones. Do you expect that normalizing the input features (either by setting their range to [-1,1] or by subtracting their mean and dividing by their standard deviation) would improve the classifier? Why yes or why not?

################# Do not write below this line #################


## [10 points, extra, not compulsory] Question 4: Gaussian Discriminant Analysis



### (a) Review and implement classification with Gradient Discriminant Analysis (GDA)

Recall the assumptions for GDA

$\begin{aligned} y & \sim \operatorname{Bernoulli}(\phi) \\ x \mid y=0 & \sim \mathcal{N}\left(\mu_{0}, \Sigma\right) \\ x \mid y=1 & \sim \mathcal{N}\left(\mu_{1}, \Sigma\right) \end{aligned}$

Recall the probability distributions:

$\begin{aligned} p(y) &=\phi^{y}(1-\phi)^{1-y} \\ p(x \mid y=0) &=\frac{1}{(2 \pi)^{d / 2}|\Sigma|^{1 / 2}} \exp \left(-\frac{1}{2}\left(x-\mu_{0}\right)^{T} \Sigma^{-1}\left(x-\mu_{0}\right)\right) \\ p(x \mid y=1) &=\frac{1}{(2 \pi)^{d / 2}|\Sigma|^{1 / 2}} \exp \left(-\frac{1}{2}\left(x-\mu_{1}\right)^{T} \Sigma^{-1}\left(x-\mu_{1}\right)\right) \end{aligned}$

Overall, the parameters of the model are $\phi, \Sigma, \mu_{0}$ and $\mu_{1}$ and the log-likelihood is given by:

$\begin{aligned} \ell\left(\phi, \mu_{0}, \mu_{1}, \Sigma\right) &=\log \prod_{i=1}^{n} p\left(x^{(i)}, y^{(i)} ; \phi, \mu_{0}, \mu_{1}, \Sigma\right) \\ &=\log \prod_{i=1}^{n} p\left(x^{(i)} \mid y^{(i)} ; \mu_{0}, \mu_{1}, \Sigma\right) p\left(y^{(i)} ; \phi\right) \end{aligned}$

Parameters may be estimated by maximum likelihood estimate as follows:

$\begin{aligned} \phi &=\frac{1}{n} \sum_{i=1}^{n} 1\left\{y^{(i)}=1\right\} \\ \mu_{0} &=\frac{\sum_{i=1}^{n} 1\left\{y^{(i)}=0\right\} x^{(i)}}{\sum_{i=1}^{n} 1\left\{y^{(i)}=0\right\}} \\ \mu_{1} &=\frac{\sum_{i=1}^{n} 1\left\{y^{(i)}=1\right\} x^{(i)}}{\sum_{i=1}^{n} 1\left\{y^{(i)}=1\right\}} \\ \Sigma &=\frac{1}{n} \sum_{i=1}^{n}\left(x^{(i)}-\mu_{y^{(i)}}\right)\left(x^{(i)}-\mu_{y^{(i)}}\right)^{T} \end{aligned}$

Consider the data variables as from the previous questions, x and y.
For this question, we would select features $x^{(i)}_1$ and $x^{(i)}_2$ into the new varible x12, dropping the $x_0=1$ convention.

In [ ]:
# First extract the sole features x1 and x2 from x into an x12 array and reshape it to x2 vector arrays
x12 = x[:,1:]
print(x[:5,:]) # For visualization of the first 5 values
print(x12[:5,:]) # For visualization of the first 5 values
print(y[:5]) # For visualization of the first 5 values

Now code up the equations above to learn the GDA parameters from the training data.


################# Do not write above this line #################


Your code here

In [ ]:
def compute_phi(y):
  # your code here
  pass


def compute_mu0(x, y):
  # your code here
  pass


def compute_mu1(x, y):
  # your code here
  pass


def compute_sigma(x, y, mu0, mu1):
  # your code here
  pass


# computing p(x|y) for the Bayes rule
def p_x_given_y(x,mu,sigma):
  # your code here
  pass



################# Do not write below this line #################


In [ ]:
# Support functions

# Function p(y) for applying the Bayes rule
def p_y(y,phi):
    if y==1: return phi
    else: return 1-phi

In [ ]:
# Now estimate the GDA parameters
phi = compute_phi(y)
mu0 = compute_mu0(x12,y)
mu1 = compute_mu1(x12,y)
sigma = compute_sigma(x12, y, mu0, mu1)

phi,mu0,mu1,sigma

Now that we know both the distributions of $p(y)$ and $p(x|y)$, we may estimate the posterior probability for an input $x$ via Bayes Rule:

\begin{equation}
p(y \mid x)=\frac{p(x \mid y) p(y)}{p(x)}
\end{equation}
where $p(x)$ is the same for both classes and may be disregarded.

This is used to classify each data point, by comparing $p(y=1|x) \propto p(x \mid y=1) p(y=1)$ and $p(y=0|x) \propto p(x \mid y=0) p(y=0)$.

In [ ]:
selected_example=1
print('Selected example =', x12[selected_example,:])

# compute p(y=0|x) ~ p(x|y=0)*p(y=0)  &  p(y=1|x) ~ p(x|y=1)*p(y=1)

# y=0
print('p(y=0|x) ~', p_x_given_y(x12[selected_example,:],mu0,sigma)*p_y(0,phi))

# y=1
print('p(y=1|x) ~', p_x_given_y(x12[selected_example,:],mu1,sigma)*p_y(1,phi))

### (b) Plot the estimated likelihood functions, the decision boundary and write your remarks


In [ ]:
def boundary_gda(x1_vec, x2_vec, mu0, mu1, sigma, phi):
    
    x1_vec, x2_vec = np.meshgrid(x1_vec,x2_vec)
    
    f=np.zeros(x1_vec.shape)
    
    for i in range(f.shape[0]):
        for j in range(f.shape[1]):
            x12_ij = np.array( (x1_vec[i,j],x2_vec[i,j]) )
            f[i,j] = p_x_given_y(x12_ij,mu1,sigma)*p_y(1,phi) - p_x_given_y(x12_ij,mu0,sigma)*p_y(0,phi)
            
    return x1_vec, x2_vec, f


x1_vec = np.linspace(df_x_pl["x1"].min()-1,df_x_pl["x1"].max()+1,200);
x2_vec = np.linspace(df_x_pl["x2"].min()-1,df_x_pl["x2"].max()+1,200);

x1_vec, x2_vec, f = boundary_gda(x1_vec, x2_vec, mu0, mu1, sigma, phi)

In [ ]:
from matplotlib import cm
from scipy.stats import multivariate_normal

# Define Gaussian pdfs
rv0 = multivariate_normal(mu0, sigma)
rv1 = multivariate_normal(mu1, sigma)

pairx12 = np.dstack((x1_vec, x2_vec))

# plot pdf contours
plt.contourf(x1_vec, x2_vec, rv0.pdf(pairx12),alpha=0.5,cmap=cm.Reds)
plt.contourf(x1_vec, x2_vec, rv1.pdf(pairx12),alpha=0.35,cmap=cm.Blues)

# Add the GDA classification to the plot
sns.scatterplot(x="x1", y="x2", hue="y", data=df_x_pl);
plt.contour(x1_vec, x2_vec, f, colors="red", levels=[0])

plt.ylim(df_x_pl["x2"].min()-1,df_x_pl["x2"].max()+1)
plt.xlim(df_x_pl["x1"].min()-1,df_x_pl["x1"].max()+1)

In [ ]:
# For comparison with the Logistic Regression boundary

# Generate vector to plot decision boundary
x1vec = np.linspace(df_x_pl["x1"].min()-1,df_x_pl["x1"].max()+1,2)

# Plot raw data
sns.scatterplot(x="x1", y="x2", hue="y", data=df_x_pl)

# Plot decision boundary
log, = plt.plot(x1vec,(-x1vec*theta_GA[1]-theta_GA[0])/theta_GA[2], color="red")
gda = plt.contour(x1_vec, x2_vec, f, colors="green", levels=[0])

plt.legend([log, gda.collections[0]],['logistic regression','GDA'])

plt.ylim(df_x_pl["x2"].min()-1,df_x_pl["x2"].max()+1)
plt.xlim(df_x_pl["x1"].min()-1,df_x_pl["x1"].max()+1)

# plt.legend()
plt.show()

Write now your considerations. Discuss in particular:
- Gaussian Discriminant Analysis makes stronger modelling assumptions than logistic regression. When may this be helpful and where may this be harmful?

Credits for material: Andrew Ng, C. Combier